### ISSUE TITLE
Support embedded HTML

### ISSUE THREAD

**Issue by xcatliu** [martinheidegger/markdown-it-replace-link#5]
Does this support embedded HTML like this:

```md
[Hello](test)

<a href="test2">Hello2</a>
```

to:

```html
<p><a href="http://me.com/test">Hello</a></p>

<a href="http://me.com/test2">Hello2</a>
```

**Comment by xcatliu** [comment]
It seems that this can be achieved in this way: https://github.com/nasa8x/markdown-it-redirect/blob/master/src/index.js#L15

**Comment by martinheidegger** [comment]
Added support for html tags in 1.2.0
