### ISSUE TITLE
Fail to parse `<center>![](~/35)`

### ISSUE THREAD

**Issue by jinzcdev** [martinheidegger/markdown-it-replace-link#6]
I found it unable to parse `<center>![](~/35)`

**Comment by martinheidegger** [comment]
@jinzcdev Thank you for having interest in this library. I added a testcase in https://github.com/martinheidegger/markdown-it-replace-link/commit/5d9a48856cddba7ac5fc10baccebedf44a2df6b9 to verify this.

If you mix html  + markdown you need to put in an empty line in order for it to be processed. Like this:

`<center>![](~/35)` ↓

```md
<center>

![](~/35)
```

Maybe this behavior can be chanced as part of the Markdown-it settings. But this library can not support it, sorry.
